---
container_name: my-app
image: nginx


resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "400m"


service:
  type: ClusterIP
  port: 8080
  targetPort: 80
