apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cop
  name: cop
spec:
  ports:
  - name: http
    port: 8082
    protocol: TCP
    targetPort: 80